##
##  Makefile -- Build procedure for sample dav_cms Apache module
##  Autogenerated via ``apxs -n dav_cms -g''.
##

builddir=$(shell pwd)
top_srcdir=/usr/local/apache2
top_builddir=/usr/local/apache2
include /usr/local/apache2/build/special.mk

# Added aditional warnings.
CFLAGS=-Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Werror
#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEF=-Dmy_define=my_value
#INC=-Imy/include/dir
#LIB=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_dav_cms.o mod_dav_cms.lo mod_dav_cms.slo mod_dav_cms.la dav_cms_props.o 

#   simple test
test: reload
	lynx -mime_header http://localhost/dav_cms

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

#  Documentation with doxygen
doc: 
	doxygen
